-- Insert councils data to fix report submission foreign key constraint
INSERT INTO public.councils (name, city, state, contact_email, contact_phone) VALUES
('Bennett University', 'Greater Noida', 'Uttar Pradesh', 'info@bennett.edu.in', NULL),
('Adityapur Municipal Corporation', 'Adityapur', 'Jharkhand', 'contact@adityapur.gov.in', NULL),
('Chakradharpur Municipality', 'Chakradharpur', 'Jharkhand', 'contact@chakradharpur.gov.in', NULL),
('Chaibasa Municipality', 'Chaibasa', 'Jharkhand', 'contact@chaibasa.gov.in', NULL),
('Chatra Municipality', 'Chatra', 'Jharkhand', 'contact@chatra.gov.in', NULL),
('Chirkunda Municipality', 'Chirkunda', 'Jharkhand', 'contact@chirkunda.gov.in', NULL),
('Dumka Municipality', 'Dumka', 'Jharkhand', 'contact@dumka.gov.in', NULL),
('Fusro Municipality', 'Fusro', 'Jharkhand', 'contact@fusro.gov.in', NULL),
('Garhwa Municipality', 'Garhwa', 'Jharkhand', 'contact@garhwa.gov.in', NULL),
('Giridih Municipality', 'Giridih', 'Jharkhand', 'contact@giridih.gov.in', NULL),
('Godda Municipality', 'Godda', 'Jharkhand', 'contact@godda.gov.in', NULL),
('Gumla Municipality', 'Gumla', 'Jharkhand', 'contact@gumla.gov.in', NULL),
('Hazaribagh Municipality', 'Hazaribagh', 'Jharkhand', 'contact@hazaribagh.gov.in', NULL),
('Jamshedpur NAC', 'Jamshedpur', 'Jharkhand', 'contact@jamshedpur.gov.in', NULL),
('Jhumri Telaiya Municipality', 'Jhumri Telaiya', 'Jharkhand', 'contact@jhumritelaiya.gov.in', NULL),
('Jugsalai Municipality', 'Jugsalai', 'Jharkhand', 'contact@jugsalai.gov.in', NULL),
('Kapali Municipality', 'Kapali', 'Jharkhand', 'contact@kapali.gov.in', NULL),
('Lohardaga Municipality', 'Lohardaga', 'Jharkhand', 'contact@lohardaga.gov.in', NULL),
('Madhupur Municipality', 'Madhupur', 'Jharkhand', 'contact@madhupur.gov.in', NULL),
('Mihijam Municipality', 'Mihijam', 'Jharkhand', 'contact@mihijam.gov.in', NULL),
('Pakur Municipality', 'Pakur', 'Jharkhand', 'contact@pakur.gov.in', NULL),
('Rajmahal Municipality', 'Rajmahal', 'Jharkhand', 'contact@rajmahal.gov.in', NULL),
('Sahebganj Municipality', 'Sahebganj', 'Jharkhand', 'contact@sahebganj.gov.in', NULL),
('Simdega Municipality', 'Simdega', 'Jharkhand', 'contact@simdega.gov.in', NULL);