// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zaymnihhizooxnjozibm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpheW1uaWhoaXpvb3huam96aWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNDYyOTMsImV4cCI6MjA3MjkyMjI5M30.wRyfEKTcY3bPoMNbow9q9RJJEjeSdcY8lHC8GK2GTF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});